version: '3.8'

services:
  get-chat-id-bot:
    build: 
      context: .
    environment:
      - TZ=Asia/Dhaka  # Set timezone to Dhaka
    container_name: get-chat-id-bot
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "main.py"]